#!/bin/bash

psql -v ON_ERROR_STOP=1 --username "$DB_POSTGRES_USER" --dbname "$DB_NAME" <<-EOSQL
  CREATE USER $DB_USER PASSWORD '$DB_PASSWORD';
  GRANT USAGE ON SCHEMA public TO "$DB_USER";
  GRANT CREATE ON SCHEMA public TO "$DB_USER";
  GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA public TO "$DB_USER";
  GRANT SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO "$DB_USER";
EOSQL
